"""UI category assignments for metric catalog entries."""

from __future__ import annotations

from fleet_routing.v2.models import MetricCategory

METRIC_CATEGORIES: dict[str, MetricCategory] = {
    # Distance & proximity
    "vehicle.nearest_idle_km": MetricCategory.DISTANCE,
    "vehicle.nearest_idle_km_rank": MetricCategory.DISTANCE,
    "vehicle.nearest_fleet_km": MetricCategory.DISTANCE,
    "vehicle.nearest_busy_km": MetricCategory.DISTANCE,
    "vehicle.idle_count_within_km": MetricCategory.DISTANCE,
    "vehicle.fleet_count_within_km": MetricCategory.DISTANCE,
    "vehicle.local_idle_density": MetricCategory.DISTANCE,
    "vehicle.local_fleet_density": MetricCategory.DISTANCE,
    "vehicle.is_most_crowded_in_radius": MetricCategory.DISTANCE,
    "vehicle.deadzone_size_km": MetricCategory.DISTANCE,
    "vehicle.nearest_unmatched_rider_km": MetricCategory.DEMAND,
    "vehicle.unmatched_riders_within_km": MetricCategory.DEMAND,
    "pair.reposition_travel_min": MetricCategory.DISTANCE,
    "pair.reposition_travel_km": MetricCategory.DISTANCE,
    "pair.density_ratio_dest_over_origin": MetricCategory.DISTANCE,
    "pair.deadzone_fill_ratio": MetricCategory.DISTANCE,
    # Waiting riders & demand
    "zone.pending_demand": MetricCategory.DEMAND,
    "zone.expected_demand": MetricCategory.DEMAND,
    "zone.demand_per_idle": MetricCategory.DEMAND,
    "zone.forecast_now": MetricCategory.DEMAND,
    "zone.forecast_t15": MetricCategory.DEMAND,
    "zone.forecast_t30": MetricCategory.DEMAND,
    "zone.forecast_t60": MetricCategory.DEMAND,
    "zone.forecast_rising": MetricCategory.DEMAND,
    "zone.active_event": MetricCategory.DEMAND,
    "zone.event_multiplier": MetricCategory.DEMAND,
    "trip.wait_minutes": MetricCategory.DEMAND,
    "trip.sla_remaining_min": MetricCategory.DEMAND,
    "trip.fare_estimate": MetricCategory.DEMAND,
    "trip.is_cross_zone": MetricCategory.DEMAND,
    "trip.pickup_zone_gap": MetricCategory.DEMAND,
    "trip.dropoff_zone_gap": MetricCategory.DEMAND,
    "trip.pickup_zone_forecast_rising": MetricCategory.DEMAND,
    "trip.dropoff_zone_surplus": MetricCategory.DEMAND,
    "trip.pickup_zone": MetricCategory.DEMAND,
    "trip.dropoff_zone": MetricCategory.DEMAND,
    # Zone balance
    "zone.supply": MetricCategory.ZONE,
    "zone.gap": MetricCategory.ZONE,
    "zone.surplus": MetricCategory.ZONE,
    "zone.target_supply": MetricCategory.ZONE,
    "zone.supply_shortfall": MetricCategory.ZONE,
    "zone.max_idle": MetricCategory.ZONE,
    "zone.headroom": MetricCategory.ZONE,
    "pair.target_zone_gap": MetricCategory.ZONE,
    "pair.reposition_benefit": MetricCategory.ZONE,
    # Timing & idle
    "vehicle.idle_minutes": MetricCategory.TIMING,
    "vehicle.manual_hold_remaining_min": MetricCategory.TIMING,
    "vehicle.leg_progress_pct": MetricCategory.TIMING,
    "vehicle.leg_remaining_min": MetricCategory.TIMING,
    "time.hour_of_day": MetricCategory.TIMING,
    # Vehicle status
    "vehicle.battery_pct": MetricCategory.VEHICLE,
    "vehicle.condition_pct": MetricCategory.VEHICLE,
    "vehicle.cleanliness_pct": MetricCategory.VEHICLE,
    "vehicle.is_dispatch_eligible": MetricCategory.VEHICLE,
    "vehicle.is_off_street": MetricCategory.VEHICLE,
    "vehicle.needs_charge": MetricCategory.VEHICLE,
    "vehicle.needs_cleaning": MetricCategory.VEHICLE,
    "vehicle.needs_maintenance": MetricCategory.VEHICLE,
    "vehicle.is_saturated_zone": MetricCategory.VEHICLE,
    "vehicle.projected_battery_after_pickup": MetricCategory.VEHICLE,
    "vehicle.projected_battery_after_trip": MetricCategory.VEHICLE,
    "vehicle.energy_needed_for_trip_pct": MetricCategory.VEHICLE,
    "vehicle.can_complete_trip_on_charge": MetricCategory.VEHICLE,
    # Dispatch scoring
    "pair.eta_pickup_min": MetricCategory.DISPATCH,
    "pair.dispatch_score": MetricCategory.DISPATCH,
    "pair.balance_adjustment": MetricCategory.DISPATCH,
    "pair.cross_zone_dispatch": MetricCategory.DISPATCH,
    # Fleet-wide
    "global.pending_trips": MetricCategory.FLEET,
    "global.avg_wait_min": MetricCategory.FLEET,
    "global.p95_wait_min": MetricCategory.FLEET,
    "global.fleet_utilization_pct": MetricCategory.FLEET,
    "global.deadhead_ratio": MetricCategory.FLEET,
    "global.profit": MetricCategory.FLEET,
    "global.completion_rate": MetricCategory.FLEET,
    "global.trips_per_vehicle_hour": MetricCategory.FLEET,
    "global.vehicles_needing_service": MetricCategory.FLEET,
    "global.avg_battery_pct": MetricCategory.FLEET,
    "global.worst_zone_gap": MetricCategory.FLEET,
    "global.surplus_zone_count": MetricCategory.FLEET,
    "global.deficit_zone_count": MetricCategory.FLEET,
    "global.traffic_multiplier": MetricCategory.FLEET,
    "global.surge_multiplier": MetricCategory.FLEET,
    "fleet.on_street_count": MetricCategory.FLEET,
    "fleet.at_facility_count": MetricCategory.FLEET,
    "const.value": MetricCategory.OTHER,
}
